### ISSUE TITLE
Error starting the app

### ISSUE THREAD

**Issue by ravening** [pykcel/myportfolio#1]
Im getting the below error when running the app

```
python3 dash_app/index.py
Traceback (most recent call last):
  File "dash_app/index.py", line 9, in <module>
    from pages.dashboard import dashboard_layout
  File "dash_app/pages/dashboard.py", line 9, in <module>
    from dash_app import config
ModuleNotFoundError: No module named 'dash_app'
```

**Comment by lbaligand** [comment]
You'll need to add the project path in `PYTHONPATH` i.e. go to myportfolio directory and run the following command:
`export PYTHONPATH=$PYTHONPATH:$(pwd)`

Thanks for pointing this out, I'll fix it in the code directly so that the above is not necessary

**Comment by ravening** [comment]
still no luck

```
ModuleNotFoundError: No module named 'dash_bootstrap_components'
```

**Comment by lbaligand** [comment]
I've updated requirements

**Comment by ravening** [comment]
I dont see the file `processed/master_portfolio.db`

```
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: transactions
[SQL: select distinct "date" from transactions order by "date" ASC]
```

**Comment by lbaligand** [comment]
You'll need your own SQL database, e.g. MySQL. you then need to modify `DB_PATH` in `dash_app/config.py` to point to your DB.

**Comment by ravening** [comment]
Maybe Im missing something here. I have MySQL running on my laptop. how do I connect MySQL to this app?
I have to create some tables/schema and then dump the tables right? but then it will be in sql format and will that be readable by sqlite?

**Comment by lbaligand** [comment]
Cool so if you're using MySQL modify the line in `dash_app/config.py` with the following:
`DB_PATH = "mysql+pymysql://user:pass@some_mariadb/dbname?charset=utf8mb4"`

I'm getting this from https://docs.sqlalchemy.org/en/14/dialects/mysql.html

No need to create any schema/tables but you'll need a fresh empty db to not mess with your existing dbs.

**Comment by lbaligand** [comment]
Actually we would need to modify a bit `src/db_backend.py` so that it handles MySQL. I'll quickly do that
